
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file Comment.cs instead.
*/

#region using directives

using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

#endregion

namespace traveltips.Entities
{
	///<summary>
	/// An object representation of the 'tbl_Comment' table. [No description found the database]	
	///</summary>
	[Serializable, DataObject]
	[CLSCompliant(true)]
	public abstract partial class CommentBase : EntityBase, traveltips.Entities.IComment, IEntityId<CommentKey>, System.IComparable, System.ICloneable, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private CommentEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private CommentEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private CommentEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<Comment> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>	
		[field:NonSerialized]
		public event CommentEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event CommentEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="CommentBase"/> instance.
		///</summary>
		public CommentBase()
		{
			this.entityData = new CommentEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="CommentBase"/> instance.
		///</summary>
		///<param name="idUser"></param>
		///<param name="idCongty"></param>
		///<param name="tieuDe">Id trong table Label</param>
		///<param name="noiDung">id truy xuat trong bang Label</param>
		///<param name="flag"></param>
		public CommentBase(System.Int64? idUser, System.Int64? idCongty, System.String tieuDe, 
			System.String noiDung, System.Byte? flag)
		{
			this.entityData = new CommentEntityData();
			this.backupData = null;

			this.IdUser = idUser;
			this.IdCongty = idCongty;
			this.TieuDe = tieuDe;
			this.NoiDung = noiDung;
			this.Flag = flag;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="Comment"/> instance.
		///</summary>
		///<param name="idUser"></param>
		///<param name="idCongty"></param>
		///<param name="tieuDe">Id trong table Label</param>
		///<param name="noiDung">id truy xuat trong bang Label</param>
		///<param name="flag"></param>
		public static Comment CreateComment(System.Int64? idUser, System.Int64? idCongty, System.String tieuDe, 
			System.String noiDung, System.Byte? flag)
		{
			Comment newComment = new Comment();
			newComment.IdUser = idUser;
			newComment.IdCongty = idCongty;
			newComment.TieuDe = tieuDe;
			newComment.NoiDung = noiDung;
			newComment.Flag = flag;
			return newComment;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the IdComment property. 
		///		
		/// </summary>
		/// <value>This type is bigint.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public virtual System.Int64 IdComment
		{
			get
			{
				return this.entityData.IdComment; 
			}
			
			set
			{
				if (this.entityData.IdComment == value)
					return;
					
				OnColumnChanging(CommentColumn.IdComment, this.entityData.IdComment);
				this.entityData.IdComment = value;
				this.EntityId.IdComment = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CommentColumn.IdComment, this.entityData.IdComment);
				OnPropertyChanged("IdComment");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the IdUser property. 
		///		
		/// </summary>
		/// <value>This type is bigint.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (long)0. It is up to the developer
		/// to check the value of IsIdUserNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int64? IdUser
		{
			get
			{
				return this.entityData.IdUser; 
			}
			
			set
			{
				if (this.entityData.IdUser == value)
					return;
					
				OnColumnChanging(CommentColumn.IdUser, this.entityData.IdUser);
				this.entityData.IdUser = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CommentColumn.IdUser, this.entityData.IdUser);
				OnPropertyChanged("IdUser");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the IdCongty property. 
		///		
		/// </summary>
		/// <value>This type is bigint.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (long)0. It is up to the developer
		/// to check the value of IsIdCongtyNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int64? IdCongty
		{
			get
			{
				return this.entityData.IdCongty; 
			}
			
			set
			{
				if (this.entityData.IdCongty == value)
					return;
					
				OnColumnChanging(CommentColumn.IdCongty, this.entityData.IdCongty);
				this.entityData.IdCongty = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CommentColumn.IdCongty, this.entityData.IdCongty);
				OnPropertyChanged("IdCongty");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the TieuDe property. 
		///		Id trong table Label
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute("Id trong table Label"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 200)]
		public virtual System.String TieuDe
		{
			get
			{
				return this.entityData.TieuDe; 
			}
			
			set
			{
				if (this.entityData.TieuDe == value)
					return;
					
				OnColumnChanging(CommentColumn.TieuDe, this.entityData.TieuDe);
				this.entityData.TieuDe = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CommentColumn.TieuDe, this.entityData.TieuDe);
				OnPropertyChanged("TieuDe");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the NoiDung property. 
		///		id truy xuat trong bang Label
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute("id truy xuat trong bang Label"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.String NoiDung
		{
			get
			{
				return this.entityData.NoiDung; 
			}
			
			set
			{
				if (this.entityData.NoiDung == value)
					return;
					
				OnColumnChanging(CommentColumn.NoiDung, this.entityData.NoiDung);
				this.entityData.NoiDung = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CommentColumn.NoiDung, this.entityData.NoiDung);
				OnPropertyChanged("NoiDung");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Flag property. 
		///		
		/// </summary>
		/// <value>This type is tinyint.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (byte)0. It is up to the developer
		/// to check the value of IsFlagNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public override System.Byte? Flag
		{
			get
			{
				return this.entityData.Flag; 
			}
			
			set
			{
				if (this.entityData.Flag == value)
					return;
					
				OnColumnChanging(CommentColumn.Flag, this.entityData.Flag);
				this.entityData.Flag = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CommentColumn.Flag, this.entityData.Flag);
				OnPropertyChanged("Flag");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="CongTy"/>.
		/// </summary>
		/// <value>The source CongTy for IdCongty.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual CongTy IdCongtySource
      	{
            get { return entityData.IdCongtySource; }
            set { entityData.IdCongtySource = value; }
      	}
		/// <summary>
		/// Gets or sets the source <see cref="User"/>.
		/// </summary>
		/// <value>The source User for IdUser.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual User IdUserSource
      	{
            get { return entityData.IdUserSource; }
            set { entityData.IdUserSource = value; }
      	}
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule(
				Validation.CommonRules.StringMaxLength, 
				new Validation.CommonRules.MaxLengthRuleArgs("TieuDe", "Tieu De", 200));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "tbl_Comment"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"id_Comment", "id_User", "id_Congty", "TieuDe", "NoiDung", "Flag"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as CommentEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (Comment) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<Comment>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as Comment);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed Comment Entity 
		///</summary>
		public virtual Comment Copy()
		{
			//shallow copy entity
			Comment copy = new Comment();
			copy.SuppressEntityEvents = true;
			copy.IdComment = this.IdComment;
			copy.IdUser = this.IdUser;
			copy.IdCongty = this.IdCongty;
			copy.TieuDe = this.TieuDe;
			copy.NoiDung = this.NoiDung;
			copy.Flag = this.Flag;
			
			copy.IdCongtySource = MakeCopyOf(this.IdCongtySource) as CongTy;
			copy.IdUserSource = MakeCopyOf(this.IdUserSource) as User;
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy();
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		///  Returns a Typed Comment Entity which is a deep copy of the current entity.
		///</summary>
		public virtual Comment DeepCopy()
		{
			return EntityHelper.Clone<Comment>(this as Comment);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as CommentEntityData;
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as CommentEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(CommentColumn column)
		{
			switch(column)
			{
					case CommentColumn.IdComment:
					return entityData.IdComment != _originalData.IdComment;
					case CommentColumn.IdUser:
					return entityData.IdUser != _originalData.IdUser;
					case CommentColumn.IdCongty:
					return entityData.IdCongty != _originalData.IdCongty;
					case CommentColumn.TieuDe:
					return entityData.TieuDe != _originalData.TieuDe;
					case CommentColumn.NoiDung:
					return entityData.NoiDung != _originalData.NoiDung;
					case CommentColumn.Flag:
					return entityData.Flag != _originalData.Flag;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if [has data changed]; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.IdComment != _originalData.IdComment;
			result = result || entityData.IdUser != _originalData.IdUser;
			result = result || entityData.IdCongty != _originalData.IdCongty;
			result = result || entityData.TieuDe != _originalData.TieuDe;
			result = result || entityData.NoiDung != _originalData.NoiDung;
			result = result || entityData.Flag != _originalData.Flag;
			return result;
}	
		
		#endregion

        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="CommentBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			if (Object1 is CommentBase)
				return Equals(this, (CommentBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="CommentBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.IdComment.GetHashCode() ^ 
					((this.IdUser == null) ? string.Empty : this.IdUser.ToString()).GetHashCode() ^ 
					((this.IdCongty == null) ? string.Empty : this.IdCongty.ToString()).GetHashCode() ^ 
					((this.TieuDe == null) ? string.Empty : this.TieuDe.ToString()).GetHashCode() ^ 
					((this.NoiDung == null) ? string.Empty : this.NoiDung.ToString()).GetHashCode() ^ 
					((this.Flag == null) ? string.Empty : this.Flag.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="CommentBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(CommentBase toObject)
		{
			if (toObject == null)
				return false;
			return Equals(this, toObject);
		}
		
		
		///<summary>
		/// Determines whether the specified <see cref="CommentBase"/> instances are considered equal.
		///</summary>
		///<param name="Object1">The first <see cref="CommentBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="CommentBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool Equals(CommentBase Object1, CommentBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.IdComment != Object2.IdComment)
				equal = false;
			if ( Object1.IdUser != null && Object2.IdUser != null )
			{
				if (Object1.IdUser != Object2.IdUser)
					equal = false;
			}
			else if (Object1.IdUser == null ^ Object2.IdUser == null )
			{
				equal = false;
			}
			if ( Object1.IdCongty != null && Object2.IdCongty != null )
			{
				if (Object1.IdCongty != Object2.IdCongty)
					equal = false;
			}
			else if (Object1.IdCongty == null ^ Object2.IdCongty == null )
			{
				equal = false;
			}
			if ( Object1.TieuDe != null && Object2.TieuDe != null )
			{
				if (Object1.TieuDe != Object2.TieuDe)
					equal = false;
			}
			else if (Object1.TieuDe == null ^ Object2.TieuDe == null )
			{
				equal = false;
			}
			if ( Object1.NoiDung != null && Object2.NoiDung != null )
			{
				if (Object1.NoiDung != Object2.NoiDung)
					equal = false;
			}
			else if (Object1.NoiDung == null ^ Object2.NoiDung == null )
			{
				equal = false;
			}
			if ( Object1.Flag != null && Object2.Flag != null )
			{
				if (Object1.Flag != Object2.Flag)
					equal = false;
			}
			else if (Object1.Flag == null ^ Object2.Flag == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((CommentBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static CommentComparer GetComparer()
        {
            return new CommentComparer();
        }
        */

        // Comparer delegates back to Comment
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(Comment rhs, CommentColumn which)
        {
            switch (which)
            {
            	
            	
            	case CommentColumn.IdComment:
            		return this.IdComment.CompareTo(rhs.IdComment);
            		
            		                 
            	
            	
            	case CommentColumn.IdUser:
            		return this.IdUser.Value.CompareTo(rhs.IdUser.Value);
            		
            		                 
            	
            	
            	case CommentColumn.IdCongty:
            		return this.IdCongty.Value.CompareTo(rhs.IdCongty.Value);
            		
            		                 
            	
            	
            	case CommentColumn.TieuDe:
            		return this.TieuDe.CompareTo(rhs.TieuDe);
            		
            		                 
            	
            	
            	case CommentColumn.NoiDung:
            		return this.NoiDung.CompareTo(rhs.NoiDung);
            		
            		                 
            	
            	
            	case CommentColumn.Flag:
            		return this.Flag.Value.CompareTo(rhs.Flag.Value);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<CommentKey> Members
		
		// member variable for the EntityId property
		private CommentKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual CommentKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new CommentKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("Comment")
					.Append("|").Append( this.IdComment.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{7}{6}- IdComment: {0}{6}- IdUser: {1}{6}- IdCongty: {2}{6}- TieuDe: {3}{6}- NoiDung: {4}{6}- Flag: {5}{6}", 
				this.IdComment,
				(this.IdUser == null) ? string.Empty : this.IdUser.ToString(),
				(this.IdCongty == null) ? string.Empty : this.IdCongty.ToString(),
				(this.TieuDe == null) ? string.Empty : this.TieuDe.ToString(),
				(this.NoiDung == null) ? string.Empty : this.NoiDung.ToString(),
				(this.Flag == null) ? string.Empty : this.Flag.ToString(),
				System.Environment.NewLine, 
				this.GetType());
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'tbl_Comment' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class CommentEntityData : ICloneable
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
			/// <summary>			
			/// id_Comment : 
			/// </summary>
			/// <remarks>Member of the primary key of the underlying table "tbl_Comment"</remarks>
			public System.Int64 IdComment;
				
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// id_User : 
		/// </summary>
		public System.Int64?		  IdUser = null;
		
		/// <summary>
		/// id_Congty : 
		/// </summary>
		public System.Int64?		  IdCongty = null;
		
		/// <summary>
		/// TieuDe : Id trong table Label
		/// </summary>
		public System.String		  TieuDe = null;
		
		/// <summary>
		/// NoiDung : id truy xuat trong bang Label
		/// </summary>
		public System.String		  NoiDung = null;
		
		/// <summary>
		/// Flag : 
		/// </summary>
		public System.Byte?		  Flag = null;
		#endregion
			
		#region Source Foreign Key Property
				
		private CongTy _idCongtySource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="CongTy"/>.
		/// </summary>
		/// <value>The source CongTy for IdCongty.</value>
        [XmlIgnore()]
		[Browsable(false)]
		public virtual CongTy IdCongtySource
      	{
            get { return this._idCongtySource; }
            set { this._idCongtySource = value; }
      	}
		private User _idUserSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="User"/>.
		/// </summary>
		/// <value>The source User for IdUser.</value>
        [XmlIgnore()]
		[Browsable(false)]
		public virtual User IdUserSource
      	{
            get { return this._idUserSource; }
            set { this._idUserSource = value; }
      	}
		#endregion
		#endregion Variable Declarations
	
		#region Data Properties

		#endregion Data Properties
		
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			CommentEntityData _tmp = new CommentEntityData();
						
			_tmp.IdComment = this.IdComment;
			
			_tmp.IdUser = this.IdUser;
			_tmp.IdCongty = this.IdCongty;
			_tmp.TieuDe = this.TieuDe;
			_tmp.NoiDung = this.NoiDung;
			_tmp.Flag = this.Flag;
			
			#region Source Parent Composite Entities
			if (this.IdCongtySource != null)
				_tmp.IdCongtySource = MakeCopyOf(this.IdCongtySource) as CongTy;
			if (this.IdUserSource != null)
				_tmp.IdUserSource = MakeCopyOf(this.IdUserSource) as User;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct



		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CommentColumn"/> which has raised the event.</param>
		public void OnColumnChanging(CommentColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CommentColumn"/> which has raised the event.</param>
		public void OnColumnChanged(CommentColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CommentColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public void OnColumnChanging(CommentColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
				EntityManager.StopTracking(entityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				CommentEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new CommentEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CommentColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public void OnColumnChanged(CommentColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				CommentEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new CommentEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region CommentEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="Comment"/> object.
	/// </remarks>
	public class CommentEventArgs : System.EventArgs
	{
		private CommentColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the CommentEventArgs class.
		///</summary>
		public CommentEventArgs(CommentColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the CommentEventArgs class.
		///</summary>
		public CommentEventArgs(CommentColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The CommentColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="CommentColumn" />
		public CommentColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all Comment related events.
	///</summary>
	public delegate void CommentEventHandler(object sender, CommentEventArgs e);
	
	#region CommentComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class CommentComparer : System.Collections.Generic.IComparer<Comment>
	{
		CommentColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:CommentComparer"/> class.
        /// </summary>
		public CommentComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:CommentComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public CommentComparer(CommentColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="Comment"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="Comment"/> to compare.</param>
        /// <param name="b">The second <c>Comment</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(Comment a, Comment b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(Comment entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(Comment a, Comment b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public CommentColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region CommentKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="Comment"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class CommentKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the CommentKey class.
		/// </summary>
		public CommentKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the CommentKey class.
		/// </summary>
		public CommentKey(CommentBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.IdComment = entity.IdComment;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the CommentKey class.
		/// </summary>
		public CommentKey(System.Int64 idComment)
		{
			#region Init Properties

			this.IdComment = idComment;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private CommentBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public CommentBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the IdComment property
		private System.Int64 _idComment;
		
		/// <summary>
		/// Gets or sets the IdComment property.
		/// </summary>
		public System.Int64 IdComment
		{
			get { return _idComment; }
			set
			{
				if ( this.Entity != null )
					this.Entity.IdComment = value;
				
				_idComment = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				IdComment = ( values["IdComment"] != null ) ? (System.Int64) EntityUtil.ChangeType(values["IdComment"], typeof(System.Int64)) : (long)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("IdComment", IdComment);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("IdComment: {0}{1}",
								IdComment,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region CommentColumn Enum
	
	/// <summary>
	/// Enumerate the Comment columns.
	/// </summary>
	[Serializable]
	public enum CommentColumn : int
	{
		/// <summary>
		/// IdComment : 
		/// </summary>
		[EnumTextValue("id_Comment")]
		[ColumnEnum("id_Comment", typeof(System.Int64), System.Data.DbType.Int64, true, true, false)]
		IdComment = 1,
		/// <summary>
		/// IdUser : 
		/// </summary>
		[EnumTextValue("id_User")]
		[ColumnEnum("id_User", typeof(System.Int64), System.Data.DbType.Int64, false, false, true)]
		IdUser = 2,
		/// <summary>
		/// IdCongty : 
		/// </summary>
		[EnumTextValue("id_Congty")]
		[ColumnEnum("id_Congty", typeof(System.Int64), System.Data.DbType.Int64, false, false, true)]
		IdCongty = 3,
		/// <summary>
		/// TieuDe : Id trong table Label
		/// </summary>
		[EnumTextValue("TieuDe")]
		[ColumnEnum("TieuDe", typeof(System.String), System.Data.DbType.String, false, false, true, 200)]
		TieuDe = 4,
		/// <summary>
		/// NoiDung : id truy xuat trong bang Label
		/// </summary>
		[EnumTextValue("NoiDung")]
		[ColumnEnum("NoiDung", typeof(System.String), System.Data.DbType.String, false, false, true)]
		NoiDung = 5,
		/// <summary>
		/// Flag : 
		/// </summary>
		[EnumTextValue("Flag")]
		[ColumnEnum("Flag", typeof(System.Byte), System.Data.DbType.Byte, false, false, true)]
		Flag = 6
	}//End enum

	#endregion CommentColumn Enum

} // end namespace
