using System;
using System.ComponentModel;

namespace traveltips.Entities
{
	/// <summary>
	///		The data structure representation of the 'tbl_DichVu' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IDichVu 
	{
		/// <summary>			
		/// id_DichVu : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "tbl_DichVu"</remarks>
		System.Int64 IdDichVu { get; set; }
				
		
		
		/// <summary>
		/// id_CongTy : 
		/// </summary>
		System.Int64?  IdCongTy  { get; set; }
		
		/// <summary>
		/// TenDV : 
		/// </summary>
		System.String  TenDv  { get; set; }
		
		/// <summary>
		/// MaDV : 
		/// </summary>
		System.String  MaDv  { get; set; }
		
		/// <summary>
		/// MotaNgan : 
		/// </summary>
		System.String  MotaNgan  { get; set; }
		
		/// <summary>
		/// MotaChiTiet : 
		/// </summary>
		System.String  MotaChiTiet  { get; set; }
		
		/// <summary>
		/// Flag : 
		/// </summary>
		System.Byte?  Flag  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


