using System;
using System.ComponentModel;

namespace traveltips.Entities
{
	/// <summary>
	///		The data structure representation of the 'tbl_Comment' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IComment 
	{
		/// <summary>			
		/// id_Comment : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "tbl_Comment"</remarks>
		System.Int64 IdComment { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.Int64 OriginalIdComment { get; set; }
			
		
		
		/// <summary>
		/// id_User : 
		/// </summary>
		System.Int64?  IdUser  { get; set; }
		
		/// <summary>
		/// id_Congty : 
		/// </summary>
		System.Int64?  IdCongty  { get; set; }
		
		/// <summary>
		/// TieuDe : Id trong table Label
		/// </summary>
		System.String  TieuDe  { get; set; }
		
		/// <summary>
		/// NoiDung : id truy xuat trong bang Label
		/// </summary>
		System.String  NoiDung  { get; set; }
		
		/// <summary>
		/// Flag : 
		/// </summary>
		System.Byte?  Flag  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


