using System;
using System.ComponentModel;

namespace traveltips.Entities
{
	/// <summary>
	///		The data structure representation of the 'tbl_Duong' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IDuong 
	{
		/// <summary>			
		/// id_Duong : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "tbl_Duong"</remarks>
		System.Int64 IdDuong { get; set; }
				
		
		
		/// <summary>
		/// id_Quan : 
		/// </summary>
		System.Int64?  IdQuan  { get; set; }
		
		/// <summary>
		/// TenDuong : 
		/// </summary>
		System.String  TenDuong  { get; set; }
		
		/// <summary>
		/// MaDuong : 
		/// </summary>
		System.Byte[]  MaDuong  { get; set; }
		
		/// <summary>
		/// MoTa : 
		/// </summary>
		System.String  MoTa  { get; set; }
		
		/// <summary>
		/// Flag : 
		/// </summary>
		System.Byte?  Flag  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


