using System;
using System.ComponentModel;

namespace traveltips.Entities
{
	/// <summary>
	///		The data structure representation of the 'tbl_Gallery' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IGallery 
	{
		/// <summary>			
		/// id_Gallery : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "tbl_Gallery"</remarks>
		System.Int64 IdGallery { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.Int64 OriginalIdGallery { get; set; }
			
		
		
		/// <summary>
		/// id_CongTy : 
		/// </summary>
		System.Int64?  IdCongTy  { get; set; }
		
		/// <summary>
		/// TenAnh : 
		/// </summary>
		System.String  TenAnh  { get; set; }
		
		/// <summary>
		/// DuongDan : 
		/// </summary>
		System.String  DuongDan  { get; set; }
		
		/// <summary>
		/// MoTa : 
		/// </summary>
		System.String  MoTa  { get; set; }
		
		/// <summary>
		/// Flag : 
		/// </summary>
		System.Byte?  Flag  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


