using System;
using System.ComponentModel;

namespace traveltips.Entities
{
	/// <summary>
	///		The data structure representation of the 'tbl_SanPham' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface ISanPham 
	{
		/// <summary>			
		/// id_SanPham : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "tbl_SanPham"</remarks>
		System.Int64 IdSanPham { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.Int64 OriginalIdSanPham { get; set; }
			
		
		
		/// <summary>
		/// id_CongTy : 
		/// </summary>
		System.Int64?  IdCongTy  { get; set; }
		
		/// <summary>
		/// id_LoaiSP : 
		/// </summary>
		System.Int64?  IdLoaiSp  { get; set; }
		
		/// <summary>
		/// id_TuDien : MaSP, TenSP duoc lay tu bang Tu Dien
		/// </summary>
		System.Int64?  IdTuDien  { get; set; }
		
		/// <summary>
		/// TenSP : 
		/// </summary>
		System.String  TenSp  { get; set; }
		
		/// <summary>
		/// MaSP : 
		/// </summary>
		System.String  MaSp  { get; set; }
		
		/// <summary>
		/// Gia : 
		/// </summary>
		System.Decimal?  Gia  { get; set; }
		
		/// <summary>
		/// MoTaNgan : 
		/// </summary>
		System.String  MoTaNgan  { get; set; }
		
		/// <summary>
		/// MoTaChiTiet : 
		/// </summary>
		System.String  MoTaChiTiet  { get; set; }
		
		/// <summary>
		/// AnhMinhHoa : 
		/// </summary>
		System.Byte[]  AnhMinhHoa  { get; set; }
		
		/// <summary>
		/// Flag : 
		/// </summary>
		System.Byte?  Flag  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation thuocTinhSanPhamIdSanPham
		/// </summary>	
		TList<ThuocTinhSanPham> ThuocTinhSanPhamCollection {  get;  set;}	

		#endregion Data Properties

	}
}


