using System;
using System.ComponentModel;

namespace traveltips.Entities
{
	/// <summary>
	///		The data structure representation of the 'tbl_TinTuc' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface ITinTuc 
	{
		/// <summary>			
		/// id_TinTuc : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "tbl_TinTuc"</remarks>
		System.Int64 IdTinTuc { get; set; }
				
		
		
		/// <summary>
		/// id_CongTy : 
		/// </summary>
		System.Int64?  IdCongTy  { get; set; }
		
		/// <summary>
		/// TieuDe : 
		/// </summary>
		System.String  TieuDe  { get; set; }
		
		/// <summary>
		/// MoTaNgan : 
		/// </summary>
		System.String  MoTaNgan  { get; set; }
		
		/// <summary>
		/// MoTaChiTiet : 
		/// </summary>
		System.String  MoTaChiTiet  { get; set; }
		
		/// <summary>
		/// KhuyenMai : 
		/// </summary>
		System.Boolean?  KhuyenMai  { get; set; }
		
		/// <summary>
		/// Flag : 
		/// </summary>
		System.Byte?  Flag  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


