
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file LoaiSp.cs instead.
*/

#region using directives

using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

#endregion

namespace traveltips.Entities
{
	///<summary>
	/// An object representation of the 'tbl_LoaiSP' table. [No description found the database]	
	///</summary>
	[Serializable, DataObject]
	[CLSCompliant(true)]
	public abstract partial class LoaiSpBase : EntityBase, traveltips.Entities.ILoaiSp, IEntityId<LoaiSpKey>, System.IComparable, System.ICloneable, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private LoaiSpEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private LoaiSpEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private LoaiSpEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<LoaiSp> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>	
		[field:NonSerialized]
		public event LoaiSpEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event LoaiSpEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="LoaiSpBase"/> instance.
		///</summary>
		public LoaiSpBase()
		{
			this.entityData = new LoaiSpEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="LoaiSpBase"/> instance.
		///</summary>
		///<param name="idLoaiSp"></param>
		///<param name="idLoaiSpCha"></param>
		///<param name="tenLoaiSp"></param>
		///<param name="maLoaiSp"></param>
		///<param name="moTa"></param>
		///<param name="flag"></param>
		public LoaiSpBase(System.Int64 idLoaiSp, System.Int64? idLoaiSpCha, System.String tenLoaiSp, 
			System.String maLoaiSp, System.String moTa, System.Byte? flag)
		{
			this.entityData = new LoaiSpEntityData();
			this.backupData = null;

			this.IdLoaiSp = idLoaiSp;
			this.IdLoaiSpCha = idLoaiSpCha;
			this.TenLoaiSp = tenLoaiSp;
			this.MaLoaiSp = maLoaiSp;
			this.MoTa = moTa;
			this.Flag = flag;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="LoaiSp"/> instance.
		///</summary>
		///<param name="idLoaiSp"></param>
		///<param name="idLoaiSpCha"></param>
		///<param name="tenLoaiSp"></param>
		///<param name="maLoaiSp"></param>
		///<param name="moTa"></param>
		///<param name="flag"></param>
		public static LoaiSp CreateLoaiSp(System.Int64 idLoaiSp, System.Int64? idLoaiSpCha, System.String tenLoaiSp, 
			System.String maLoaiSp, System.String moTa, System.Byte? flag)
		{
			LoaiSp newLoaiSp = new LoaiSp();
			newLoaiSp.IdLoaiSp = idLoaiSp;
			newLoaiSp.IdLoaiSpCha = idLoaiSpCha;
			newLoaiSp.TenLoaiSp = tenLoaiSp;
			newLoaiSp.MaLoaiSp = maLoaiSp;
			newLoaiSp.MoTa = moTa;
			newLoaiSp.Flag = flag;
			return newLoaiSp;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the IdLoaiSp property. 
		///		
		/// </summary>
		/// <value>This type is bigint.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, false, false)]
		public virtual System.Int64 IdLoaiSp
		{
			get
			{
				return this.entityData.IdLoaiSp; 
			}
			
			set
			{
				if (this.entityData.IdLoaiSp == value)
					return;
					
				OnColumnChanging(LoaiSpColumn.IdLoaiSp, this.entityData.IdLoaiSp);
				this.entityData.IdLoaiSp = value;
				this.EntityId.IdLoaiSp = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(LoaiSpColumn.IdLoaiSp, this.entityData.IdLoaiSp);
				OnPropertyChanged("IdLoaiSp");
			}
		}
		
		/// <summary>
		/// 	Get the original value of the id_LoaiSP property.
		///		
		/// </summary>
		/// <remarks>This is the original value of the id_LoaiSP property.</remarks>
		/// <value>This type is bigint</value>
		[BrowsableAttribute(false)/*, XmlIgnoreAttribute()*/]
		public  virtual System.Int64 OriginalIdLoaiSp
		{
			get { return this.entityData.OriginalIdLoaiSp; }
			set { this.entityData.OriginalIdLoaiSp = value; }
		}
		
		/// <summary>
		/// 	Gets or sets the IdLoaiSpCha property. 
		///		
		/// </summary>
		/// <value>This type is bigint.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (long)0. It is up to the developer
		/// to check the value of IsIdLoaiSpChaNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int64? IdLoaiSpCha
		{
			get
			{
				return this.entityData.IdLoaiSpCha; 
			}
			
			set
			{
				if (this.entityData.IdLoaiSpCha == value)
					return;
					
				OnColumnChanging(LoaiSpColumn.IdLoaiSpCha, this.entityData.IdLoaiSpCha);
				this.entityData.IdLoaiSpCha = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(LoaiSpColumn.IdLoaiSpCha, this.entityData.IdLoaiSpCha);
				OnPropertyChanged("IdLoaiSpCha");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the TenLoaiSp property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 255)]
		public virtual System.String TenLoaiSp
		{
			get
			{
				return this.entityData.TenLoaiSp; 
			}
			
			set
			{
				if (this.entityData.TenLoaiSp == value)
					return;
					
				OnColumnChanging(LoaiSpColumn.TenLoaiSp, this.entityData.TenLoaiSp);
				this.entityData.TenLoaiSp = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(LoaiSpColumn.TenLoaiSp, this.entityData.TenLoaiSp);
				OnPropertyChanged("TenLoaiSp");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the MaLoaiSp property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String MaLoaiSp
		{
			get
			{
				return this.entityData.MaLoaiSp; 
			}
			
			set
			{
				if (this.entityData.MaLoaiSp == value)
					return;
					
				OnColumnChanging(LoaiSpColumn.MaLoaiSp, this.entityData.MaLoaiSp);
				this.entityData.MaLoaiSp = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(LoaiSpColumn.MaLoaiSp, this.entityData.MaLoaiSp);
				OnPropertyChanged("MaLoaiSp");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the MoTa property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String MoTa
		{
			get
			{
				return this.entityData.MoTa; 
			}
			
			set
			{
				if (this.entityData.MoTa == value)
					return;
					
				OnColumnChanging(LoaiSpColumn.MoTa, this.entityData.MoTa);
				this.entityData.MoTa = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(LoaiSpColumn.MoTa, this.entityData.MoTa);
				OnPropertyChanged("MoTa");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Flag property. 
		///		
		/// </summary>
		/// <value>This type is tinyint.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (byte)0. It is up to the developer
		/// to check the value of IsFlagNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public override System.Byte? Flag
		{
			get
			{
				return this.entityData.Flag; 
			}
			
			set
			{
				if (this.entityData.Flag == value)
					return;
					
				OnColumnChanging(LoaiSpColumn.Flag, this.entityData.Flag);
				this.entityData.Flag = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(LoaiSpColumn.Flag, this.entityData.Flag);
				OnPropertyChanged("Flag");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		#endregion
		
		#region Children Collections
	
		/// <summary>
		///	Holds a collection of SanPham objects
		///	which are related to this object through the relation FK_tbl_SanPham_tbl_LoaiSP
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<SanPham> SanPhamCollection
		{
			get { return entityData.SanPhamCollection; }
			set { entityData.SanPhamCollection = value; }	
		}
		#endregion Children Collections
		
		#endregion
		
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule(
				Validation.CommonRules.StringMaxLength, 
				new Validation.CommonRules.MaxLengthRuleArgs("TenLoaiSp", "Ten Loai Sp", 255));
			ValidationRules.AddRule(
				Validation.CommonRules.StringMaxLength, 
				new Validation.CommonRules.MaxLengthRuleArgs("MaLoaiSp", "Ma Loai Sp", 50));
			ValidationRules.AddRule(
				Validation.CommonRules.StringMaxLength, 
				new Validation.CommonRules.MaxLengthRuleArgs("MoTa", "Mo Ta", 50));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "tbl_LoaiSP"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"id_LoaiSP", "id_LoaiSPCha", "TenLoaiSP", "MaLoaiSP", "MoTa", "Flag"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as LoaiSpEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (LoaiSp) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<LoaiSp>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as LoaiSp);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed LoaiSp Entity 
		///</summary>
		public virtual LoaiSp Copy()
		{
			//shallow copy entity
			LoaiSp copy = new LoaiSp();
			copy.SuppressEntityEvents = true;
			copy.IdLoaiSp = this.IdLoaiSp;
			copy.OriginalIdLoaiSp = this.OriginalIdLoaiSp;
			copy.IdLoaiSpCha = this.IdLoaiSpCha;
			copy.TenLoaiSp = this.TenLoaiSp;
			copy.MaLoaiSp = this.MaLoaiSp;
			copy.MoTa = this.MoTa;
			copy.Flag = this.Flag;
			
		
			//deep copy nested objects
			copy.SanPhamCollection = (TList<SanPham>) MakeCopyOf(this.SanPhamCollection); 
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy();
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		///  Returns a Typed LoaiSp Entity which is a deep copy of the current entity.
		///</summary>
		public virtual LoaiSp DeepCopy()
		{
			return EntityHelper.Clone<LoaiSp>(this as LoaiSp);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as LoaiSpEntityData;
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as LoaiSpEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(LoaiSpColumn column)
		{
			switch(column)
			{
					case LoaiSpColumn.IdLoaiSp:
					return entityData.IdLoaiSp != _originalData.IdLoaiSp;
					case LoaiSpColumn.IdLoaiSpCha:
					return entityData.IdLoaiSpCha != _originalData.IdLoaiSpCha;
					case LoaiSpColumn.TenLoaiSp:
					return entityData.TenLoaiSp != _originalData.TenLoaiSp;
					case LoaiSpColumn.MaLoaiSp:
					return entityData.MaLoaiSp != _originalData.MaLoaiSp;
					case LoaiSpColumn.MoTa:
					return entityData.MoTa != _originalData.MoTa;
					case LoaiSpColumn.Flag:
					return entityData.Flag != _originalData.Flag;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if [has data changed]; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.IdLoaiSp != _originalData.IdLoaiSp;
			result = result || entityData.IdLoaiSpCha != _originalData.IdLoaiSpCha;
			result = result || entityData.TenLoaiSp != _originalData.TenLoaiSp;
			result = result || entityData.MaLoaiSp != _originalData.MaLoaiSp;
			result = result || entityData.MoTa != _originalData.MoTa;
			result = result || entityData.Flag != _originalData.Flag;
			return result;
}	
		
		#endregion

        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="LoaiSpBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			if (Object1 is LoaiSpBase)
				return Equals(this, (LoaiSpBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="LoaiSpBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.IdLoaiSp.GetHashCode() ^ 
					((this.IdLoaiSpCha == null) ? string.Empty : this.IdLoaiSpCha.ToString()).GetHashCode() ^ 
					((this.TenLoaiSp == null) ? string.Empty : this.TenLoaiSp.ToString()).GetHashCode() ^ 
					((this.MaLoaiSp == null) ? string.Empty : this.MaLoaiSp.ToString()).GetHashCode() ^ 
					((this.MoTa == null) ? string.Empty : this.MoTa.ToString()).GetHashCode() ^ 
					((this.Flag == null) ? string.Empty : this.Flag.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="LoaiSpBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(LoaiSpBase toObject)
		{
			if (toObject == null)
				return false;
			return Equals(this, toObject);
		}
		
		
		///<summary>
		/// Determines whether the specified <see cref="LoaiSpBase"/> instances are considered equal.
		///</summary>
		///<param name="Object1">The first <see cref="LoaiSpBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="LoaiSpBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool Equals(LoaiSpBase Object1, LoaiSpBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.IdLoaiSp != Object2.IdLoaiSp)
				equal = false;
			if ( Object1.IdLoaiSpCha != null && Object2.IdLoaiSpCha != null )
			{
				if (Object1.IdLoaiSpCha != Object2.IdLoaiSpCha)
					equal = false;
			}
			else if (Object1.IdLoaiSpCha == null ^ Object2.IdLoaiSpCha == null )
			{
				equal = false;
			}
			if ( Object1.TenLoaiSp != null && Object2.TenLoaiSp != null )
			{
				if (Object1.TenLoaiSp != Object2.TenLoaiSp)
					equal = false;
			}
			else if (Object1.TenLoaiSp == null ^ Object2.TenLoaiSp == null )
			{
				equal = false;
			}
			if ( Object1.MaLoaiSp != null && Object2.MaLoaiSp != null )
			{
				if (Object1.MaLoaiSp != Object2.MaLoaiSp)
					equal = false;
			}
			else if (Object1.MaLoaiSp == null ^ Object2.MaLoaiSp == null )
			{
				equal = false;
			}
			if ( Object1.MoTa != null && Object2.MoTa != null )
			{
				if (Object1.MoTa != Object2.MoTa)
					equal = false;
			}
			else if (Object1.MoTa == null ^ Object2.MoTa == null )
			{
				equal = false;
			}
			if ( Object1.Flag != null && Object2.Flag != null )
			{
				if (Object1.Flag != Object2.Flag)
					equal = false;
			}
			else if (Object1.Flag == null ^ Object2.Flag == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((LoaiSpBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static LoaiSpComparer GetComparer()
        {
            return new LoaiSpComparer();
        }
        */

        // Comparer delegates back to LoaiSp
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(LoaiSp rhs, LoaiSpColumn which)
        {
            switch (which)
            {
            	
            	
            	case LoaiSpColumn.IdLoaiSp:
            		return this.IdLoaiSp.CompareTo(rhs.IdLoaiSp);
            		
            		                 
            	
            	
            	case LoaiSpColumn.IdLoaiSpCha:
            		return this.IdLoaiSpCha.Value.CompareTo(rhs.IdLoaiSpCha.Value);
            		
            		                 
            	
            	
            	case LoaiSpColumn.TenLoaiSp:
            		return this.TenLoaiSp.CompareTo(rhs.TenLoaiSp);
            		
            		                 
            	
            	
            	case LoaiSpColumn.MaLoaiSp:
            		return this.MaLoaiSp.CompareTo(rhs.MaLoaiSp);
            		
            		                 
            	
            	
            	case LoaiSpColumn.MoTa:
            		return this.MoTa.CompareTo(rhs.MoTa);
            		
            		                 
            	
            	
            	case LoaiSpColumn.Flag:
            		return this.Flag.Value.CompareTo(rhs.Flag.Value);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<LoaiSpKey> Members
		
		// member variable for the EntityId property
		private LoaiSpKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual LoaiSpKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new LoaiSpKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("LoaiSp")
					.Append("|").Append( this.IdLoaiSp.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{7}{6}- IdLoaiSp: {0}{6}- IdLoaiSpCha: {1}{6}- TenLoaiSp: {2}{6}- MaLoaiSp: {3}{6}- MoTa: {4}{6}- Flag: {5}{6}", 
				this.IdLoaiSp,
				(this.IdLoaiSpCha == null) ? string.Empty : this.IdLoaiSpCha.ToString(),
				(this.TenLoaiSp == null) ? string.Empty : this.TenLoaiSp.ToString(),
				(this.MaLoaiSp == null) ? string.Empty : this.MaLoaiSp.ToString(),
				(this.MoTa == null) ? string.Empty : this.MoTa.ToString(),
				(this.Flag == null) ? string.Empty : this.Flag.ToString(),
				System.Environment.NewLine, 
				this.GetType());
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'tbl_LoaiSP' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class LoaiSpEntityData : ICloneable
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
			/// <summary>			
			/// id_LoaiSP : 
			/// </summary>
			/// <remarks>Member of the primary key of the underlying table "tbl_LoaiSP"</remarks>
			public System.Int64 IdLoaiSp;
				
			/// <summary>
			/// keep a copy of the original so it can be used for editable primary keys.
			/// </summary>
			public System.Int64 OriginalIdLoaiSp;
			
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// id_LoaiSPCha : 
		/// </summary>
		public System.Int64?		  IdLoaiSpCha = null;
		
		/// <summary>
		/// TenLoaiSP : 
		/// </summary>
		public System.String		  TenLoaiSp = null;
		
		/// <summary>
		/// MaLoaiSP : 
		/// </summary>
		public System.String		  MaLoaiSp = null;
		
		/// <summary>
		/// MoTa : 
		/// </summary>
		public System.String		  MoTa = null;
		
		/// <summary>
		/// Flag : 
		/// </summary>
		public System.Byte?		  Flag = null;
		#endregion
			
		#region Source Foreign Key Property
				
		#endregion
		#endregion Variable Declarations
	
		#region Data Properties

		#region SanPhamCollection
		
		private TList<SanPham> sanPhamIdLoaiSp;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation sanPhamIdLoaiSp
		/// </summary>	
		public TList<SanPham> SanPhamCollection
		{
			get
			{
				if (sanPhamIdLoaiSp == null)
				{
				sanPhamIdLoaiSp = new TList<SanPham>();
				}
	
				return sanPhamIdLoaiSp;
			}
			set { sanPhamIdLoaiSp = value; }
		}
		
		#endregion

		#endregion Data Properties
		
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			LoaiSpEntityData _tmp = new LoaiSpEntityData();
						
			_tmp.IdLoaiSp = this.IdLoaiSp;
			_tmp.OriginalIdLoaiSp = this.OriginalIdLoaiSp;
			
			_tmp.IdLoaiSpCha = this.IdLoaiSpCha;
			_tmp.TenLoaiSp = this.TenLoaiSp;
			_tmp.MaLoaiSp = this.MaLoaiSp;
			_tmp.MoTa = this.MoTa;
			_tmp.Flag = this.Flag;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			if (this.sanPhamIdLoaiSp != null)
				_tmp.SanPhamCollection = (TList<SanPham>) MakeCopyOf(this.SanPhamCollection); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct



		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="LoaiSpColumn"/> which has raised the event.</param>
		public void OnColumnChanging(LoaiSpColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="LoaiSpColumn"/> which has raised the event.</param>
		public void OnColumnChanged(LoaiSpColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="LoaiSpColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public void OnColumnChanging(LoaiSpColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
				EntityManager.StopTracking(entityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				LoaiSpEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new LoaiSpEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="LoaiSpColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public void OnColumnChanged(LoaiSpColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				LoaiSpEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new LoaiSpEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region LoaiSpEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="LoaiSp"/> object.
	/// </remarks>
	public class LoaiSpEventArgs : System.EventArgs
	{
		private LoaiSpColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the LoaiSpEventArgs class.
		///</summary>
		public LoaiSpEventArgs(LoaiSpColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the LoaiSpEventArgs class.
		///</summary>
		public LoaiSpEventArgs(LoaiSpColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The LoaiSpColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="LoaiSpColumn" />
		public LoaiSpColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all LoaiSp related events.
	///</summary>
	public delegate void LoaiSpEventHandler(object sender, LoaiSpEventArgs e);
	
	#region LoaiSpComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class LoaiSpComparer : System.Collections.Generic.IComparer<LoaiSp>
	{
		LoaiSpColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:LoaiSpComparer"/> class.
        /// </summary>
		public LoaiSpComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:LoaiSpComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public LoaiSpComparer(LoaiSpColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="LoaiSp"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="LoaiSp"/> to compare.</param>
        /// <param name="b">The second <c>LoaiSp</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(LoaiSp a, LoaiSp b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(LoaiSp entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(LoaiSp a, LoaiSp b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public LoaiSpColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region LoaiSpKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="LoaiSp"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class LoaiSpKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the LoaiSpKey class.
		/// </summary>
		public LoaiSpKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the LoaiSpKey class.
		/// </summary>
		public LoaiSpKey(LoaiSpBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.IdLoaiSp = entity.IdLoaiSp;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the LoaiSpKey class.
		/// </summary>
		public LoaiSpKey(System.Int64 idLoaiSp)
		{
			#region Init Properties

			this.IdLoaiSp = idLoaiSp;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private LoaiSpBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public LoaiSpBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the IdLoaiSp property
		private System.Int64 _idLoaiSp;
		
		/// <summary>
		/// Gets or sets the IdLoaiSp property.
		/// </summary>
		public System.Int64 IdLoaiSp
		{
			get { return _idLoaiSp; }
			set
			{
				if ( this.Entity != null )
					this.Entity.IdLoaiSp = value;
				
				_idLoaiSp = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				IdLoaiSp = ( values["IdLoaiSp"] != null ) ? (System.Int64) EntityUtil.ChangeType(values["IdLoaiSp"], typeof(System.Int64)) : (long)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("IdLoaiSp", IdLoaiSp);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("IdLoaiSp: {0}{1}",
								IdLoaiSp,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region LoaiSpColumn Enum
	
	/// <summary>
	/// Enumerate the LoaiSp columns.
	/// </summary>
	[Serializable]
	public enum LoaiSpColumn : int
	{
		/// <summary>
		/// IdLoaiSp : 
		/// </summary>
		[EnumTextValue("id_LoaiSP")]
		[ColumnEnum("id_LoaiSP", typeof(System.Int64), System.Data.DbType.Int64, true, false, false)]
		IdLoaiSp = 1,
		/// <summary>
		/// IdLoaiSpCha : 
		/// </summary>
		[EnumTextValue("id_LoaiSPCha")]
		[ColumnEnum("id_LoaiSPCha", typeof(System.Int64), System.Data.DbType.Int64, false, false, true)]
		IdLoaiSpCha = 2,
		/// <summary>
		/// TenLoaiSp : 
		/// </summary>
		[EnumTextValue("TenLoaiSP")]
		[ColumnEnum("TenLoaiSP", typeof(System.String), System.Data.DbType.String, false, false, true, 255)]
		TenLoaiSp = 3,
		/// <summary>
		/// MaLoaiSp : 
		/// </summary>
		[EnumTextValue("MaLoaiSP")]
		[ColumnEnum("MaLoaiSP", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 50)]
		MaLoaiSp = 4,
		/// <summary>
		/// MoTa : 
		/// </summary>
		[EnumTextValue("MoTa")]
		[ColumnEnum("MoTa", typeof(System.String), System.Data.DbType.String, false, false, true, 50)]
		MoTa = 5,
		/// <summary>
		/// Flag : 
		/// </summary>
		[EnumTextValue("Flag")]
		[ColumnEnum("Flag", typeof(System.Byte), System.Data.DbType.Byte, false, false, true)]
		Flag = 6
	}//End enum

	#endregion LoaiSpColumn Enum

} // end namespace
