
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file ThanhPho.cs instead.
*/

#region using directives

using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

#endregion

namespace traveltips.Entities
{
	///<summary>
	/// An object representation of the 'tbl_ThanhPho' table. [No description found the database]	
	///</summary>
	[Serializable, DataObject]
	[CLSCompliant(true)]
	public abstract partial class ThanhPhoBase : EntityBase, traveltips.Entities.IThanhPho, IEntityId<ThanhPhoKey>, System.IComparable, System.ICloneable, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private ThanhPhoEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private ThanhPhoEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private ThanhPhoEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<ThanhPho> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>	
		[field:NonSerialized]
		public event ThanhPhoEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event ThanhPhoEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="ThanhPhoBase"/> instance.
		///</summary>
		public ThanhPhoBase()
		{
			this.entityData = new ThanhPhoEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="ThanhPhoBase"/> instance.
		///</summary>
		///<param name="idQuocGia"></param>
		///<param name="tenTp"></param>
		///<param name="maTp"></param>
		///<param name="mota"></param>
		///<param name="flag"></param>
		public ThanhPhoBase(System.Int64? idQuocGia, System.String tenTp, System.String maTp, 
			System.String mota, System.Byte? flag)
		{
			this.entityData = new ThanhPhoEntityData();
			this.backupData = null;

			this.IdQuocGia = idQuocGia;
			this.TenTp = tenTp;
			this.MaTp = maTp;
			this.Mota = mota;
			this.Flag = flag;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="ThanhPho"/> instance.
		///</summary>
		///<param name="idQuocGia"></param>
		///<param name="tenTp"></param>
		///<param name="maTp"></param>
		///<param name="mota"></param>
		///<param name="flag"></param>
		public static ThanhPho CreateThanhPho(System.Int64? idQuocGia, System.String tenTp, System.String maTp, 
			System.String mota, System.Byte? flag)
		{
			ThanhPho newThanhPho = new ThanhPho();
			newThanhPho.IdQuocGia = idQuocGia;
			newThanhPho.TenTp = tenTp;
			newThanhPho.MaTp = maTp;
			newThanhPho.Mota = mota;
			newThanhPho.Flag = flag;
			return newThanhPho;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the IdThanhPho property. 
		///		
		/// </summary>
		/// <value>This type is bigint.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public virtual System.Int64 IdThanhPho
		{
			get
			{
				return this.entityData.IdThanhPho; 
			}
			
			set
			{
				if (this.entityData.IdThanhPho == value)
					return;
					
				OnColumnChanging(ThanhPhoColumn.IdThanhPho, this.entityData.IdThanhPho);
				this.entityData.IdThanhPho = value;
				this.EntityId.IdThanhPho = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ThanhPhoColumn.IdThanhPho, this.entityData.IdThanhPho);
				OnPropertyChanged("IdThanhPho");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the IdQuocGia property. 
		///		
		/// </summary>
		/// <value>This type is bigint.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (long)0. It is up to the developer
		/// to check the value of IsIdQuocGiaNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int64? IdQuocGia
		{
			get
			{
				return this.entityData.IdQuocGia; 
			}
			
			set
			{
				if (this.entityData.IdQuocGia == value)
					return;
					
				OnColumnChanging(ThanhPhoColumn.IdQuocGia, this.entityData.IdQuocGia);
				this.entityData.IdQuocGia = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ThanhPhoColumn.IdQuocGia, this.entityData.IdQuocGia);
				OnPropertyChanged("IdQuocGia");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the TenTp property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 100)]
		public virtual System.String TenTp
		{
			get
			{
				return this.entityData.TenTp; 
			}
			
			set
			{
				if (this.entityData.TenTp == value)
					return;
					
				OnColumnChanging(ThanhPhoColumn.TenTp, this.entityData.TenTp);
				this.entityData.TenTp = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ThanhPhoColumn.TenTp, this.entityData.TenTp);
				OnPropertyChanged("TenTp");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the MaTp property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String MaTp
		{
			get
			{
				return this.entityData.MaTp; 
			}
			
			set
			{
				if (this.entityData.MaTp == value)
					return;
					
				OnColumnChanging(ThanhPhoColumn.MaTp, this.entityData.MaTp);
				this.entityData.MaTp = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ThanhPhoColumn.MaTp, this.entityData.MaTp);
				OnPropertyChanged("MaTp");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Mota property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String Mota
		{
			get
			{
				return this.entityData.Mota; 
			}
			
			set
			{
				if (this.entityData.Mota == value)
					return;
					
				OnColumnChanging(ThanhPhoColumn.Mota, this.entityData.Mota);
				this.entityData.Mota = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ThanhPhoColumn.Mota, this.entityData.Mota);
				OnPropertyChanged("Mota");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Flag property. 
		///		
		/// </summary>
		/// <value>This type is tinyint.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (byte)0. It is up to the developer
		/// to check the value of IsFlagNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public override System.Byte? Flag
		{
			get
			{
				return this.entityData.Flag; 
			}
			
			set
			{
				if (this.entityData.Flag == value)
					return;
					
				OnColumnChanging(ThanhPhoColumn.Flag, this.entityData.Flag);
				this.entityData.Flag = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ThanhPhoColumn.Flag, this.entityData.Flag);
				OnPropertyChanged("Flag");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="QuocGia"/>.
		/// </summary>
		/// <value>The source QuocGia for IdQuocGia.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual QuocGia IdQuocGiaSource
      	{
            get { return entityData.IdQuocGiaSource; }
            set { entityData.IdQuocGiaSource = value; }
      	}
		#endregion
		
		#region Children Collections
	
		/// <summary>
		///	Holds a collection of Quan objects
		///	which are related to this object through the relation FK_tbl_Quan_tbl_ThanhPho
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<Quan> QuanCollection
		{
			get { return entityData.QuanCollection; }
			set { entityData.QuanCollection = value; }	
		}
		#endregion Children Collections
		
		#endregion
		
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule(
				Validation.CommonRules.StringMaxLength, 
				new Validation.CommonRules.MaxLengthRuleArgs("TenTp", "Ten Tp", 100));
			ValidationRules.AddRule(
				Validation.CommonRules.StringMaxLength, 
				new Validation.CommonRules.MaxLengthRuleArgs("MaTp", "Ma Tp", 50));
			ValidationRules.AddRule(
				Validation.CommonRules.StringMaxLength, 
				new Validation.CommonRules.MaxLengthRuleArgs("Mota", "Mota", 50));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "tbl_ThanhPho"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"id_ThanhPho", "id_QuocGia", "TenTP", "MaTP", "Mota", "Flag"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as ThanhPhoEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (ThanhPho) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<ThanhPho>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as ThanhPho);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed ThanhPho Entity 
		///</summary>
		public virtual ThanhPho Copy()
		{
			//shallow copy entity
			ThanhPho copy = new ThanhPho();
			copy.SuppressEntityEvents = true;
			copy.IdThanhPho = this.IdThanhPho;
			copy.IdQuocGia = this.IdQuocGia;
			copy.TenTp = this.TenTp;
			copy.MaTp = this.MaTp;
			copy.Mota = this.Mota;
			copy.Flag = this.Flag;
			
			copy.IdQuocGiaSource = MakeCopyOf(this.IdQuocGiaSource) as QuocGia;
		
			//deep copy nested objects
			copy.QuanCollection = (TList<Quan>) MakeCopyOf(this.QuanCollection); 
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy();
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		///  Returns a Typed ThanhPho Entity which is a deep copy of the current entity.
		///</summary>
		public virtual ThanhPho DeepCopy()
		{
			return EntityHelper.Clone<ThanhPho>(this as ThanhPho);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as ThanhPhoEntityData;
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as ThanhPhoEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(ThanhPhoColumn column)
		{
			switch(column)
			{
					case ThanhPhoColumn.IdThanhPho:
					return entityData.IdThanhPho != _originalData.IdThanhPho;
					case ThanhPhoColumn.IdQuocGia:
					return entityData.IdQuocGia != _originalData.IdQuocGia;
					case ThanhPhoColumn.TenTp:
					return entityData.TenTp != _originalData.TenTp;
					case ThanhPhoColumn.MaTp:
					return entityData.MaTp != _originalData.MaTp;
					case ThanhPhoColumn.Mota:
					return entityData.Mota != _originalData.Mota;
					case ThanhPhoColumn.Flag:
					return entityData.Flag != _originalData.Flag;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if [has data changed]; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.IdThanhPho != _originalData.IdThanhPho;
			result = result || entityData.IdQuocGia != _originalData.IdQuocGia;
			result = result || entityData.TenTp != _originalData.TenTp;
			result = result || entityData.MaTp != _originalData.MaTp;
			result = result || entityData.Mota != _originalData.Mota;
			result = result || entityData.Flag != _originalData.Flag;
			return result;
}	
		
		#endregion

        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="ThanhPhoBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			if (Object1 is ThanhPhoBase)
				return Equals(this, (ThanhPhoBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="ThanhPhoBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.IdThanhPho.GetHashCode() ^ 
					((this.IdQuocGia == null) ? string.Empty : this.IdQuocGia.ToString()).GetHashCode() ^ 
					((this.TenTp == null) ? string.Empty : this.TenTp.ToString()).GetHashCode() ^ 
					((this.MaTp == null) ? string.Empty : this.MaTp.ToString()).GetHashCode() ^ 
					((this.Mota == null) ? string.Empty : this.Mota.ToString()).GetHashCode() ^ 
					((this.Flag == null) ? string.Empty : this.Flag.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="ThanhPhoBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(ThanhPhoBase toObject)
		{
			if (toObject == null)
				return false;
			return Equals(this, toObject);
		}
		
		
		///<summary>
		/// Determines whether the specified <see cref="ThanhPhoBase"/> instances are considered equal.
		///</summary>
		///<param name="Object1">The first <see cref="ThanhPhoBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="ThanhPhoBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool Equals(ThanhPhoBase Object1, ThanhPhoBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.IdThanhPho != Object2.IdThanhPho)
				equal = false;
			if ( Object1.IdQuocGia != null && Object2.IdQuocGia != null )
			{
				if (Object1.IdQuocGia != Object2.IdQuocGia)
					equal = false;
			}
			else if (Object1.IdQuocGia == null ^ Object2.IdQuocGia == null )
			{
				equal = false;
			}
			if ( Object1.TenTp != null && Object2.TenTp != null )
			{
				if (Object1.TenTp != Object2.TenTp)
					equal = false;
			}
			else if (Object1.TenTp == null ^ Object2.TenTp == null )
			{
				equal = false;
			}
			if ( Object1.MaTp != null && Object2.MaTp != null )
			{
				if (Object1.MaTp != Object2.MaTp)
					equal = false;
			}
			else if (Object1.MaTp == null ^ Object2.MaTp == null )
			{
				equal = false;
			}
			if ( Object1.Mota != null && Object2.Mota != null )
			{
				if (Object1.Mota != Object2.Mota)
					equal = false;
			}
			else if (Object1.Mota == null ^ Object2.Mota == null )
			{
				equal = false;
			}
			if ( Object1.Flag != null && Object2.Flag != null )
			{
				if (Object1.Flag != Object2.Flag)
					equal = false;
			}
			else if (Object1.Flag == null ^ Object2.Flag == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((ThanhPhoBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static ThanhPhoComparer GetComparer()
        {
            return new ThanhPhoComparer();
        }
        */

        // Comparer delegates back to ThanhPho
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(ThanhPho rhs, ThanhPhoColumn which)
        {
            switch (which)
            {
            	
            	
            	case ThanhPhoColumn.IdThanhPho:
            		return this.IdThanhPho.CompareTo(rhs.IdThanhPho);
            		
            		                 
            	
            	
            	case ThanhPhoColumn.IdQuocGia:
            		return this.IdQuocGia.Value.CompareTo(rhs.IdQuocGia.Value);
            		
            		                 
            	
            	
            	case ThanhPhoColumn.TenTp:
            		return this.TenTp.CompareTo(rhs.TenTp);
            		
            		                 
            	
            	
            	case ThanhPhoColumn.MaTp:
            		return this.MaTp.CompareTo(rhs.MaTp);
            		
            		                 
            	
            	
            	case ThanhPhoColumn.Mota:
            		return this.Mota.CompareTo(rhs.Mota);
            		
            		                 
            	
            	
            	case ThanhPhoColumn.Flag:
            		return this.Flag.Value.CompareTo(rhs.Flag.Value);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<ThanhPhoKey> Members
		
		// member variable for the EntityId property
		private ThanhPhoKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual ThanhPhoKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new ThanhPhoKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("ThanhPho")
					.Append("|").Append( this.IdThanhPho.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{7}{6}- IdThanhPho: {0}{6}- IdQuocGia: {1}{6}- TenTp: {2}{6}- MaTp: {3}{6}- Mota: {4}{6}- Flag: {5}{6}", 
				this.IdThanhPho,
				(this.IdQuocGia == null) ? string.Empty : this.IdQuocGia.ToString(),
				(this.TenTp == null) ? string.Empty : this.TenTp.ToString(),
				(this.MaTp == null) ? string.Empty : this.MaTp.ToString(),
				(this.Mota == null) ? string.Empty : this.Mota.ToString(),
				(this.Flag == null) ? string.Empty : this.Flag.ToString(),
				System.Environment.NewLine, 
				this.GetType());
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'tbl_ThanhPho' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class ThanhPhoEntityData : ICloneable
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
			/// <summary>			
			/// id_ThanhPho : 
			/// </summary>
			/// <remarks>Member of the primary key of the underlying table "tbl_ThanhPho"</remarks>
			public System.Int64 IdThanhPho;
				
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// id_QuocGia : 
		/// </summary>
		public System.Int64?		  IdQuocGia = null;
		
		/// <summary>
		/// TenTP : 
		/// </summary>
		public System.String		  TenTp = null;
		
		/// <summary>
		/// MaTP : 
		/// </summary>
		public System.String		  MaTp = null;
		
		/// <summary>
		/// Mota : 
		/// </summary>
		public System.String		  Mota = null;
		
		/// <summary>
		/// Flag : 
		/// </summary>
		public System.Byte?		  Flag = null;
		#endregion
			
		#region Source Foreign Key Property
				
		private QuocGia _idQuocGiaSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="QuocGia"/>.
		/// </summary>
		/// <value>The source QuocGia for IdQuocGia.</value>
        [XmlIgnore()]
		[Browsable(false)]
		public virtual QuocGia IdQuocGiaSource
      	{
            get { return this._idQuocGiaSource; }
            set { this._idQuocGiaSource = value; }
      	}
		#endregion
		#endregion Variable Declarations
	
		#region Data Properties

		#region QuanCollection
		
		private TList<Quan> quanIdThanhPho;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation quanIdThanhPho
		/// </summary>	
		public TList<Quan> QuanCollection
		{
			get
			{
				if (quanIdThanhPho == null)
				{
				quanIdThanhPho = new TList<Quan>();
				}
	
				return quanIdThanhPho;
			}
			set { quanIdThanhPho = value; }
		}
		
		#endregion

		#endregion Data Properties
		
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			ThanhPhoEntityData _tmp = new ThanhPhoEntityData();
						
			_tmp.IdThanhPho = this.IdThanhPho;
			
			_tmp.IdQuocGia = this.IdQuocGia;
			_tmp.TenTp = this.TenTp;
			_tmp.MaTp = this.MaTp;
			_tmp.Mota = this.Mota;
			_tmp.Flag = this.Flag;
			
			#region Source Parent Composite Entities
			if (this.IdQuocGiaSource != null)
				_tmp.IdQuocGiaSource = MakeCopyOf(this.IdQuocGiaSource) as QuocGia;
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			if (this.quanIdThanhPho != null)
				_tmp.QuanCollection = (TList<Quan>) MakeCopyOf(this.QuanCollection); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct



		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="ThanhPhoColumn"/> which has raised the event.</param>
		public void OnColumnChanging(ThanhPhoColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="ThanhPhoColumn"/> which has raised the event.</param>
		public void OnColumnChanged(ThanhPhoColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="ThanhPhoColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public void OnColumnChanging(ThanhPhoColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
				EntityManager.StopTracking(entityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				ThanhPhoEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new ThanhPhoEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="ThanhPhoColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public void OnColumnChanged(ThanhPhoColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				ThanhPhoEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new ThanhPhoEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region ThanhPhoEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="ThanhPho"/> object.
	/// </remarks>
	public class ThanhPhoEventArgs : System.EventArgs
	{
		private ThanhPhoColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the ThanhPhoEventArgs class.
		///</summary>
		public ThanhPhoEventArgs(ThanhPhoColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the ThanhPhoEventArgs class.
		///</summary>
		public ThanhPhoEventArgs(ThanhPhoColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The ThanhPhoColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="ThanhPhoColumn" />
		public ThanhPhoColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all ThanhPho related events.
	///</summary>
	public delegate void ThanhPhoEventHandler(object sender, ThanhPhoEventArgs e);
	
	#region ThanhPhoComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class ThanhPhoComparer : System.Collections.Generic.IComparer<ThanhPho>
	{
		ThanhPhoColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:ThanhPhoComparer"/> class.
        /// </summary>
		public ThanhPhoComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:ThanhPhoComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public ThanhPhoComparer(ThanhPhoColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="ThanhPho"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="ThanhPho"/> to compare.</param>
        /// <param name="b">The second <c>ThanhPho</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(ThanhPho a, ThanhPho b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(ThanhPho entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(ThanhPho a, ThanhPho b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public ThanhPhoColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region ThanhPhoKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="ThanhPho"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class ThanhPhoKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the ThanhPhoKey class.
		/// </summary>
		public ThanhPhoKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the ThanhPhoKey class.
		/// </summary>
		public ThanhPhoKey(ThanhPhoBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.IdThanhPho = entity.IdThanhPho;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the ThanhPhoKey class.
		/// </summary>
		public ThanhPhoKey(System.Int64 idThanhPho)
		{
			#region Init Properties

			this.IdThanhPho = idThanhPho;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private ThanhPhoBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public ThanhPhoBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the IdThanhPho property
		private System.Int64 _idThanhPho;
		
		/// <summary>
		/// Gets or sets the IdThanhPho property.
		/// </summary>
		public System.Int64 IdThanhPho
		{
			get { return _idThanhPho; }
			set
			{
				if ( this.Entity != null )
					this.Entity.IdThanhPho = value;
				
				_idThanhPho = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				IdThanhPho = ( values["IdThanhPho"] != null ) ? (System.Int64) EntityUtil.ChangeType(values["IdThanhPho"], typeof(System.Int64)) : (long)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("IdThanhPho", IdThanhPho);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("IdThanhPho: {0}{1}",
								IdThanhPho,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region ThanhPhoColumn Enum
	
	/// <summary>
	/// Enumerate the ThanhPho columns.
	/// </summary>
	[Serializable]
	public enum ThanhPhoColumn : int
	{
		/// <summary>
		/// IdThanhPho : 
		/// </summary>
		[EnumTextValue("id_ThanhPho")]
		[ColumnEnum("id_ThanhPho", typeof(System.Int64), System.Data.DbType.Int64, true, true, false)]
		IdThanhPho = 1,
		/// <summary>
		/// IdQuocGia : 
		/// </summary>
		[EnumTextValue("id_QuocGia")]
		[ColumnEnum("id_QuocGia", typeof(System.Int64), System.Data.DbType.Int64, false, false, true)]
		IdQuocGia = 2,
		/// <summary>
		/// TenTp : 
		/// </summary>
		[EnumTextValue("TenTP")]
		[ColumnEnum("TenTP", typeof(System.String), System.Data.DbType.String, false, false, true, 100)]
		TenTp = 3,
		/// <summary>
		/// MaTp : 
		/// </summary>
		[EnumTextValue("MaTP")]
		[ColumnEnum("MaTP", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 50)]
		MaTp = 4,
		/// <summary>
		/// Mota : 
		/// </summary>
		[EnumTextValue("Mota")]
		[ColumnEnum("Mota", typeof(System.String), System.Data.DbType.String, false, false, true, 50)]
		Mota = 5,
		/// <summary>
		/// Flag : 
		/// </summary>
		[EnumTextValue("Flag")]
		[ColumnEnum("Flag", typeof(System.Byte), System.Data.DbType.Byte, false, false, true)]
		Flag = 6
	}//End enum

	#endregion ThanhPhoColumn Enum

} // end namespace
