
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file TuDien.cs instead.
*/

#region using directives

using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

#endregion

namespace traveltips.Entities
{
	///<summary>
	/// An object representation of the 'tbl_TuDien' table. [No description found the database]	
	///</summary>
	[Serializable, DataObject]
	[CLSCompliant(true)]
	public abstract partial class TuDienBase : EntityBase, traveltips.Entities.ITuDien, IEntityId<TuDienKey>, System.IComparable, System.ICloneable, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private TuDienEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private TuDienEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private TuDienEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<TuDien> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>	
		[field:NonSerialized]
		public event TuDienEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event TuDienEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="TuDienBase"/> instance.
		///</summary>
		public TuDienBase()
		{
			this.entityData = new TuDienEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="TuDienBase"/> instance.
		///</summary>
		///<param name="idTuDien"></param>
		///<param name="idDanhMuc"></param>
		///<param name="tenTu"></param>
		///<param name="maTu"></param>
		///<param name="nhomTu">NhomTu: Dai dien cho mot nhom nhat dinh phai co tu dien (phuc vu cho viec Load len theo nhom). Vi du: Mon An, Thuc Uong, Quoc Gia, Tinh, Thanh Pho,......</param>
		///<param name="moTa"></param>
		///<param name="flag"></param>
		public TuDienBase(System.Int64 idTuDien, System.Int64? idDanhMuc, System.String tenTu, 
			System.String maTu, System.String nhomTu, System.String moTa, System.Byte? flag)
		{
			this.entityData = new TuDienEntityData();
			this.backupData = null;

			this.IdTuDien = idTuDien;
			this.IdDanhMuc = idDanhMuc;
			this.TenTu = tenTu;
			this.MaTu = maTu;
			this.NhomTu = nhomTu;
			this.MoTa = moTa;
			this.Flag = flag;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="TuDien"/> instance.
		///</summary>
		///<param name="idTuDien"></param>
		///<param name="idDanhMuc"></param>
		///<param name="tenTu"></param>
		///<param name="maTu"></param>
		///<param name="nhomTu">NhomTu: Dai dien cho mot nhom nhat dinh phai co tu dien (phuc vu cho viec Load len theo nhom). Vi du: Mon An, Thuc Uong, Quoc Gia, Tinh, Thanh Pho,......</param>
		///<param name="moTa"></param>
		///<param name="flag"></param>
		public static TuDien CreateTuDien(System.Int64 idTuDien, System.Int64? idDanhMuc, System.String tenTu, 
			System.String maTu, System.String nhomTu, System.String moTa, System.Byte? flag)
		{
			TuDien newTuDien = new TuDien();
			newTuDien.IdTuDien = idTuDien;
			newTuDien.IdDanhMuc = idDanhMuc;
			newTuDien.TenTu = tenTu;
			newTuDien.MaTu = maTu;
			newTuDien.NhomTu = nhomTu;
			newTuDien.MoTa = moTa;
			newTuDien.Flag = flag;
			return newTuDien;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the IdTuDien property. 
		///		
		/// </summary>
		/// <value>This type is bigint.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, false, false)]
		public virtual System.Int64 IdTuDien
		{
			get
			{
				return this.entityData.IdTuDien; 
			}
			
			set
			{
				if (this.entityData.IdTuDien == value)
					return;
					
				OnColumnChanging(TuDienColumn.IdTuDien, this.entityData.IdTuDien);
				this.entityData.IdTuDien = value;
				this.EntityId.IdTuDien = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(TuDienColumn.IdTuDien, this.entityData.IdTuDien);
				OnPropertyChanged("IdTuDien");
			}
		}
		
		/// <summary>
		/// 	Get the original value of the id_TuDien property.
		///		
		/// </summary>
		/// <remarks>This is the original value of the id_TuDien property.</remarks>
		/// <value>This type is bigint</value>
		[BrowsableAttribute(false)/*, XmlIgnoreAttribute()*/]
		public  virtual System.Int64 OriginalIdTuDien
		{
			get { return this.entityData.OriginalIdTuDien; }
			set { this.entityData.OriginalIdTuDien = value; }
		}
		
		/// <summary>
		/// 	Gets or sets the IdDanhMuc property. 
		///		
		/// </summary>
		/// <value>This type is bigint.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (long)0. It is up to the developer
		/// to check the value of IsIdDanhMucNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int64? IdDanhMuc
		{
			get
			{
				return this.entityData.IdDanhMuc; 
			}
			
			set
			{
				if (this.entityData.IdDanhMuc == value)
					return;
					
				OnColumnChanging(TuDienColumn.IdDanhMuc, this.entityData.IdDanhMuc);
				this.entityData.IdDanhMuc = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(TuDienColumn.IdDanhMuc, this.entityData.IdDanhMuc);
				OnPropertyChanged("IdDanhMuc");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the TenTu property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String TenTu
		{
			get
			{
				return this.entityData.TenTu; 
			}
			
			set
			{
				if (this.entityData.TenTu == value)
					return;
					
				OnColumnChanging(TuDienColumn.TenTu, this.entityData.TenTu);
				this.entityData.TenTu = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(TuDienColumn.TenTu, this.entityData.TenTu);
				OnPropertyChanged("TenTu");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the MaTu property. 
		///		
		/// </summary>
		/// <value>This type is nchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 10)]
		public virtual System.String MaTu
		{
			get
			{
				return this.entityData.MaTu; 
			}
			
			set
			{
				if (this.entityData.MaTu == value)
					return;
					
				OnColumnChanging(TuDienColumn.MaTu, this.entityData.MaTu);
				this.entityData.MaTu = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(TuDienColumn.MaTu, this.entityData.MaTu);
				OnPropertyChanged("MaTu");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the NhomTu property. 
		///		NhomTu: Dai dien cho mot nhom nhat dinh phai co tu dien (phuc vu cho viec Load len theo nhom). Vi du: Mon An, Thuc Uong, Quoc Gia, Tinh, Thanh Pho,......
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute("NhomTu: Dai dien cho mot nhom nhat dinh phai co tu dien (phuc vu cho viec Load len theo nhom). Vi du: Mon An, Thuc Uong, Quoc Gia, Tinh, Thanh Pho,......"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String NhomTu
		{
			get
			{
				return this.entityData.NhomTu; 
			}
			
			set
			{
				if (this.entityData.NhomTu == value)
					return;
					
				OnColumnChanging(TuDienColumn.NhomTu, this.entityData.NhomTu);
				this.entityData.NhomTu = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(TuDienColumn.NhomTu, this.entityData.NhomTu);
				OnPropertyChanged("NhomTu");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the MoTa property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String MoTa
		{
			get
			{
				return this.entityData.MoTa; 
			}
			
			set
			{
				if (this.entityData.MoTa == value)
					return;
					
				OnColumnChanging(TuDienColumn.MoTa, this.entityData.MoTa);
				this.entityData.MoTa = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(TuDienColumn.MoTa, this.entityData.MoTa);
				OnPropertyChanged("MoTa");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Flag property. 
		///		
		/// </summary>
		/// <value>This type is tinyint.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (byte)0. It is up to the developer
		/// to check the value of IsFlagNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public override System.Byte? Flag
		{
			get
			{
				return this.entityData.Flag; 
			}
			
			set
			{
				if (this.entityData.Flag == value)
					return;
					
				OnColumnChanging(TuDienColumn.Flag, this.entityData.Flag);
				this.entityData.Flag = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(TuDienColumn.Flag, this.entityData.Flag);
				OnPropertyChanged("Flag");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule(
				Validation.CommonRules.StringMaxLength, 
				new Validation.CommonRules.MaxLengthRuleArgs("TenTu", "Ten Tu", 50));
			ValidationRules.AddRule(
				Validation.CommonRules.StringMaxLength, 
				new Validation.CommonRules.MaxLengthRuleArgs("MaTu", "Ma Tu", 10));
			ValidationRules.AddRule(
				Validation.CommonRules.StringMaxLength, 
				new Validation.CommonRules.MaxLengthRuleArgs("NhomTu", "Nhom Tu", 50));
			ValidationRules.AddRule(
				Validation.CommonRules.StringMaxLength, 
				new Validation.CommonRules.MaxLengthRuleArgs("MoTa", "Mo Ta", 50));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "tbl_TuDien"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"id_TuDien", "id_DanhMuc", "TenTu", "MaTu", "NhomTu", "MoTa", "Flag"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as TuDienEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (TuDien) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<TuDien>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as TuDien);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed TuDien Entity 
		///</summary>
		public virtual TuDien Copy()
		{
			//shallow copy entity
			TuDien copy = new TuDien();
			copy.SuppressEntityEvents = true;
			copy.IdTuDien = this.IdTuDien;
			copy.OriginalIdTuDien = this.OriginalIdTuDien;
			copy.IdDanhMuc = this.IdDanhMuc;
			copy.TenTu = this.TenTu;
			copy.MaTu = this.MaTu;
			copy.NhomTu = this.NhomTu;
			copy.MoTa = this.MoTa;
			copy.Flag = this.Flag;
			
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy();
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		///  Returns a Typed TuDien Entity which is a deep copy of the current entity.
		///</summary>
		public virtual TuDien DeepCopy()
		{
			return EntityHelper.Clone<TuDien>(this as TuDien);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as TuDienEntityData;
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as TuDienEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(TuDienColumn column)
		{
			switch(column)
			{
					case TuDienColumn.IdTuDien:
					return entityData.IdTuDien != _originalData.IdTuDien;
					case TuDienColumn.IdDanhMuc:
					return entityData.IdDanhMuc != _originalData.IdDanhMuc;
					case TuDienColumn.TenTu:
					return entityData.TenTu != _originalData.TenTu;
					case TuDienColumn.MaTu:
					return entityData.MaTu != _originalData.MaTu;
					case TuDienColumn.NhomTu:
					return entityData.NhomTu != _originalData.NhomTu;
					case TuDienColumn.MoTa:
					return entityData.MoTa != _originalData.MoTa;
					case TuDienColumn.Flag:
					return entityData.Flag != _originalData.Flag;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if [has data changed]; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.IdTuDien != _originalData.IdTuDien;
			result = result || entityData.IdDanhMuc != _originalData.IdDanhMuc;
			result = result || entityData.TenTu != _originalData.TenTu;
			result = result || entityData.MaTu != _originalData.MaTu;
			result = result || entityData.NhomTu != _originalData.NhomTu;
			result = result || entityData.MoTa != _originalData.MoTa;
			result = result || entityData.Flag != _originalData.Flag;
			return result;
}	
		
		#endregion

        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="TuDienBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			if (Object1 is TuDienBase)
				return Equals(this, (TuDienBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="TuDienBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.IdTuDien.GetHashCode() ^ 
					((this.IdDanhMuc == null) ? string.Empty : this.IdDanhMuc.ToString()).GetHashCode() ^ 
					((this.TenTu == null) ? string.Empty : this.TenTu.ToString()).GetHashCode() ^ 
					((this.MaTu == null) ? string.Empty : this.MaTu.ToString()).GetHashCode() ^ 
					((this.NhomTu == null) ? string.Empty : this.NhomTu.ToString()).GetHashCode() ^ 
					((this.MoTa == null) ? string.Empty : this.MoTa.ToString()).GetHashCode() ^ 
					((this.Flag == null) ? string.Empty : this.Flag.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="TuDienBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(TuDienBase toObject)
		{
			if (toObject == null)
				return false;
			return Equals(this, toObject);
		}
		
		
		///<summary>
		/// Determines whether the specified <see cref="TuDienBase"/> instances are considered equal.
		///</summary>
		///<param name="Object1">The first <see cref="TuDienBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="TuDienBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool Equals(TuDienBase Object1, TuDienBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.IdTuDien != Object2.IdTuDien)
				equal = false;
			if ( Object1.IdDanhMuc != null && Object2.IdDanhMuc != null )
			{
				if (Object1.IdDanhMuc != Object2.IdDanhMuc)
					equal = false;
			}
			else if (Object1.IdDanhMuc == null ^ Object2.IdDanhMuc == null )
			{
				equal = false;
			}
			if ( Object1.TenTu != null && Object2.TenTu != null )
			{
				if (Object1.TenTu != Object2.TenTu)
					equal = false;
			}
			else if (Object1.TenTu == null ^ Object2.TenTu == null )
			{
				equal = false;
			}
			if ( Object1.MaTu != null && Object2.MaTu != null )
			{
				if (Object1.MaTu != Object2.MaTu)
					equal = false;
			}
			else if (Object1.MaTu == null ^ Object2.MaTu == null )
			{
				equal = false;
			}
			if ( Object1.NhomTu != null && Object2.NhomTu != null )
			{
				if (Object1.NhomTu != Object2.NhomTu)
					equal = false;
			}
			else if (Object1.NhomTu == null ^ Object2.NhomTu == null )
			{
				equal = false;
			}
			if ( Object1.MoTa != null && Object2.MoTa != null )
			{
				if (Object1.MoTa != Object2.MoTa)
					equal = false;
			}
			else if (Object1.MoTa == null ^ Object2.MoTa == null )
			{
				equal = false;
			}
			if ( Object1.Flag != null && Object2.Flag != null )
			{
				if (Object1.Flag != Object2.Flag)
					equal = false;
			}
			else if (Object1.Flag == null ^ Object2.Flag == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((TuDienBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static TuDienComparer GetComparer()
        {
            return new TuDienComparer();
        }
        */

        // Comparer delegates back to TuDien
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(TuDien rhs, TuDienColumn which)
        {
            switch (which)
            {
            	
            	
            	case TuDienColumn.IdTuDien:
            		return this.IdTuDien.CompareTo(rhs.IdTuDien);
            		
            		                 
            	
            	
            	case TuDienColumn.IdDanhMuc:
            		return this.IdDanhMuc.Value.CompareTo(rhs.IdDanhMuc.Value);
            		
            		                 
            	
            	
            	case TuDienColumn.TenTu:
            		return this.TenTu.CompareTo(rhs.TenTu);
            		
            		                 
            	
            	
            	case TuDienColumn.MaTu:
            		return this.MaTu.CompareTo(rhs.MaTu);
            		
            		                 
            	
            	
            	case TuDienColumn.NhomTu:
            		return this.NhomTu.CompareTo(rhs.NhomTu);
            		
            		                 
            	
            	
            	case TuDienColumn.MoTa:
            		return this.MoTa.CompareTo(rhs.MoTa);
            		
            		                 
            	
            	
            	case TuDienColumn.Flag:
            		return this.Flag.Value.CompareTo(rhs.Flag.Value);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<TuDienKey> Members
		
		// member variable for the EntityId property
		private TuDienKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual TuDienKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new TuDienKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("TuDien")
					.Append("|").Append( this.IdTuDien.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{8}{7}- IdTuDien: {0}{7}- IdDanhMuc: {1}{7}- TenTu: {2}{7}- MaTu: {3}{7}- NhomTu: {4}{7}- MoTa: {5}{7}- Flag: {6}{7}", 
				this.IdTuDien,
				(this.IdDanhMuc == null) ? string.Empty : this.IdDanhMuc.ToString(),
				(this.TenTu == null) ? string.Empty : this.TenTu.ToString(),
				(this.MaTu == null) ? string.Empty : this.MaTu.ToString(),
				(this.NhomTu == null) ? string.Empty : this.NhomTu.ToString(),
				(this.MoTa == null) ? string.Empty : this.MoTa.ToString(),
				(this.Flag == null) ? string.Empty : this.Flag.ToString(),
				System.Environment.NewLine, 
				this.GetType());
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'tbl_TuDien' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class TuDienEntityData : ICloneable
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
			/// <summary>			
			/// id_TuDien : 
			/// </summary>
			/// <remarks>Member of the primary key of the underlying table "tbl_TuDien"</remarks>
			public System.Int64 IdTuDien;
				
			/// <summary>
			/// keep a copy of the original so it can be used for editable primary keys.
			/// </summary>
			public System.Int64 OriginalIdTuDien;
			
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// id_DanhMuc : 
		/// </summary>
		public System.Int64?		  IdDanhMuc = null;
		
		/// <summary>
		/// TenTu : 
		/// </summary>
		public System.String		  TenTu = null;
		
		/// <summary>
		/// MaTu : 
		/// </summary>
		public System.String		  MaTu = null;
		
		/// <summary>
		/// NhomTu : NhomTu: Dai dien cho mot nhom nhat dinh phai co tu dien (phuc vu cho viec Load len theo nhom). Vi du: Mon An, Thuc Uong, Quoc Gia, Tinh, Thanh Pho,......
		/// </summary>
		public System.String		  NhomTu = null;
		
		/// <summary>
		/// MoTa : 
		/// </summary>
		public System.String		  MoTa = null;
		
		/// <summary>
		/// Flag : 
		/// </summary>
		public System.Byte?		  Flag = null;
		#endregion
			
		#region Source Foreign Key Property
				
		#endregion
		#endregion Variable Declarations
	
		#region Data Properties

		#endregion Data Properties
		
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			TuDienEntityData _tmp = new TuDienEntityData();
						
			_tmp.IdTuDien = this.IdTuDien;
			_tmp.OriginalIdTuDien = this.OriginalIdTuDien;
			
			_tmp.IdDanhMuc = this.IdDanhMuc;
			_tmp.TenTu = this.TenTu;
			_tmp.MaTu = this.MaTu;
			_tmp.NhomTu = this.NhomTu;
			_tmp.MoTa = this.MoTa;
			_tmp.Flag = this.Flag;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct



		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="TuDienColumn"/> which has raised the event.</param>
		public void OnColumnChanging(TuDienColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="TuDienColumn"/> which has raised the event.</param>
		public void OnColumnChanged(TuDienColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="TuDienColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public void OnColumnChanging(TuDienColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
				EntityManager.StopTracking(entityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				TuDienEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new TuDienEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="TuDienColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public void OnColumnChanged(TuDienColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				TuDienEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new TuDienEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region TuDienEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="TuDien"/> object.
	/// </remarks>
	public class TuDienEventArgs : System.EventArgs
	{
		private TuDienColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the TuDienEventArgs class.
		///</summary>
		public TuDienEventArgs(TuDienColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the TuDienEventArgs class.
		///</summary>
		public TuDienEventArgs(TuDienColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The TuDienColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="TuDienColumn" />
		public TuDienColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all TuDien related events.
	///</summary>
	public delegate void TuDienEventHandler(object sender, TuDienEventArgs e);
	
	#region TuDienComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class TuDienComparer : System.Collections.Generic.IComparer<TuDien>
	{
		TuDienColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:TuDienComparer"/> class.
        /// </summary>
		public TuDienComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:TuDienComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public TuDienComparer(TuDienColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="TuDien"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="TuDien"/> to compare.</param>
        /// <param name="b">The second <c>TuDien</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(TuDien a, TuDien b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(TuDien entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(TuDien a, TuDien b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public TuDienColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region TuDienKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="TuDien"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class TuDienKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the TuDienKey class.
		/// </summary>
		public TuDienKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the TuDienKey class.
		/// </summary>
		public TuDienKey(TuDienBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.IdTuDien = entity.IdTuDien;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the TuDienKey class.
		/// </summary>
		public TuDienKey(System.Int64 idTuDien)
		{
			#region Init Properties

			this.IdTuDien = idTuDien;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private TuDienBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public TuDienBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the IdTuDien property
		private System.Int64 _idTuDien;
		
		/// <summary>
		/// Gets or sets the IdTuDien property.
		/// </summary>
		public System.Int64 IdTuDien
		{
			get { return _idTuDien; }
			set
			{
				if ( this.Entity != null )
					this.Entity.IdTuDien = value;
				
				_idTuDien = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				IdTuDien = ( values["IdTuDien"] != null ) ? (System.Int64) EntityUtil.ChangeType(values["IdTuDien"], typeof(System.Int64)) : (long)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("IdTuDien", IdTuDien);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("IdTuDien: {0}{1}",
								IdTuDien,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region TuDienColumn Enum
	
	/// <summary>
	/// Enumerate the TuDien columns.
	/// </summary>
	[Serializable]
	public enum TuDienColumn : int
	{
		/// <summary>
		/// IdTuDien : 
		/// </summary>
		[EnumTextValue("id_TuDien")]
		[ColumnEnum("id_TuDien", typeof(System.Int64), System.Data.DbType.Int64, true, false, false)]
		IdTuDien = 1,
		/// <summary>
		/// IdDanhMuc : 
		/// </summary>
		[EnumTextValue("id_DanhMuc")]
		[ColumnEnum("id_DanhMuc", typeof(System.Int64), System.Data.DbType.Int64, false, false, true)]
		IdDanhMuc = 2,
		/// <summary>
		/// TenTu : 
		/// </summary>
		[EnumTextValue("TenTu")]
		[ColumnEnum("TenTu", typeof(System.String), System.Data.DbType.String, false, false, true, 50)]
		TenTu = 3,
		/// <summary>
		/// MaTu : 
		/// </summary>
		[EnumTextValue("MaTu")]
		[ColumnEnum("MaTu", typeof(System.String), System.Data.DbType.StringFixedLength, false, false, true, 10)]
		MaTu = 4,
		/// <summary>
		/// NhomTu : NhomTu: Dai dien cho mot nhom nhat dinh phai co tu dien (phuc vu cho viec Load len theo nhom). Vi du: Mon An, Thuc Uong, Quoc Gia, Tinh, Thanh Pho,......
		/// </summary>
		[EnumTextValue("NhomTu")]
		[ColumnEnum("NhomTu", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 50)]
		NhomTu = 5,
		/// <summary>
		/// MoTa : 
		/// </summary>
		[EnumTextValue("MoTa")]
		[ColumnEnum("MoTa", typeof(System.String), System.Data.DbType.String, false, false, true, 50)]
		MoTa = 6,
		/// <summary>
		/// Flag : 
		/// </summary>
		[EnumTextValue("Flag")]
		[ColumnEnum("Flag", typeof(System.Byte), System.Data.DbType.Byte, false, false, true)]
		Flag = 7
	}//End enum

	#endregion TuDienColumn Enum

} // end namespace
